% Trabalho de Telecomunicacoes
% Pedro Cruz
% Thiago Barroso Perrotta

data = {'Data/100m.mat', 'Data/101m.mat', 'Data/102m.mat' ...
    'Data/103m.mat', 'Data/104m.mat', 'Data/105m.mat' ...
    'Data/106m.mat', 'Data/107m.mat', 'Data/108m.mat' ...
    'Data/109m.mat', 'Data/111m.mat', 'Data/112m.mat' ...
    'Data/113m.mat', 'Data/114m.mat', 'Data/115m.mat' ...
    'Data/116m.mat', 'Data/117m.mat', 'Data/118m.mat' ...
    'Data/119m.mat', 'Data/121m.mat', 'Data/122m.mat' ...
    'Data/123m.mat', 'Data/124m.mat', 'Data/200m.mat' ...
    'Data/201m.mat', 'Data/202m.mat', 'Data/203m.mat' ...
    'Data/205m.mat', 'Data/207m.mat', 'Data/208m.mat'};

diag = {'Supraventricular ectopy', 'Supraventricular ectopy', 'Ventricular ectopy'...
   'Supraventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy'...
   'Ventricular ectopy', 'Ventricular ectopy', 'Supraventricular ectopy'...
   'Ventricular ectopy', 'Normal', 'Supraventricular ectopy' ...
   'Supraventricular ectopy', 'Supraventricular ectopy', 'Normal' ...
   'Ventricular ectopy', 'Normal', 'Supraventricular ectopy' ...
   'Ventricular ectopy', 'Normal', 'Normal' ...
   'Ventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy' ...
   'Supraventricular ectopy', 'Supraventricular ectopy', 'Ventricular ectopy' ...
   'Ventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy'};

% for i = 1:(length(data))
%     var = peaks_variance(data{i});
%     disp(['Var for file ', data{i}, ' = ', num2str(var), 'diag = ', diag{i}]);
% end    

plot_file(data{1});