% % Trabalho de Telecomunicacoes
% % Pedro Cruz
% % Thiago Barroso Perrotta
% 
% % Names of the files that will be used
% data = ['Data/100.mat', 'Data/101.mat', 'Data/102.mat' ...
%     'Data/103.mat', 'Data/104.mat', 'Data/105.mat' ...
%     'Data/106.mat', 'Data/107.mat', 'Data/108.mat' ...
%     'Data/109.mat', 'Data/111.mat', 'Data/112.mat' ...
%     'Data/113.mat', 'Data/114.mat', 'Data/115.mat' ...
%     'Data/116.mat', 'Data/117.mat', 'Data/118.mat' ...
%     'Data/119.mat', 'Data/121.mat', 'Data/122.mat' ...
%     'Data/123.mat', 'Data/124.mat', 'Data/200.mat' ...
%     'Data/201.mat', 'Data/202.mat', 'Data/203.mat' ...
%     'Data/205.mat', 'Data/207.mat', 'Data/208.mat'];
% 
% diag = ['Supraventricular ectopy', 'Supraventricular ectopy', 'Ventricular ectopy'...
%    'Supraventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy'...
%    'Ventricular ectopy', 'Ventricular ectopy', 'Supraventricular ectopy'...
%    'Ventricular ectopy', 'Normal', 'Supraventricular ectopy' ...
%    'Supraventricular ectopy', 'Supraventricular ectopy', 'Normal' ...
%    'Ventricular ectopy', 'Normal', 'Supraventricular ectopy' ...
%    'Ventricular ectopy', 'Normal', 'Normal' ...
%    'Ventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy' ...
%    'Supraventricular ectopy', 'Supraventricular ectopy', 'Ventricular ectopy' ...
%    'Ventricular ectopy', 'Ventricular ectopy', 'Ventricular ectopy'];
% 

%plot_file( 'Data/102m.mat' );
simple_plot('Data/102m.mat');

% %fid = fopen('variances.txt','wt');  % Note the 'wt' for writing in text mode
% %fprintf(fid,'%f\n',a);  % The format string is applied to each element of a
% %fclose(fid);


